### ISSUE TITLE
localhost:5000 is a reserved port in Macs

### ISSUE THREAD

**Issue by michael4reynolds** [PlusGenie/tbot-tradingboat#4]
Localhost 5000 is reserved for Airplay on Macs

**Comment by PlusGenie** [comment]
The issue appears to stem from Apple's AirPlay Receiver occupying port 5000. Apple uses this port for the AirPlay Receiver service. To resolve this conflict, you can disable the AirPlay Receiver:

- Open System Preferences.
- Go to Sharing.
- Uncheck AirPlay Receiver.

By disabling the AirPlay Receiver, port 5000 will become available for your application.
